In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\amitm\\Desktop\\basic ml project\\data\\third_clean.csv")

In [3]:
df['Memory'] = df['Memory'].astype(str).replace('\.0','',regex = True)

In [4]:
df['Memory'] = df['Memory'].str.replace('GB','')

In [5]:
df['Memory'] = df['Memory'].str.replace('TB','000')

In [6]:
newdf = df['Memory'].str.split("+",n = 1,expand = True)

In [7]:
df['first'] = newdf[0]
df['first'] = df['first'].str.strip()

In [8]:
def applychanges(value):
    
    df['Layer1'+value] = df['first'].apply(lambda x:1 if value in x else 0)

In [9]:
listtoapply = ['HDD','SSD','Hybrid','Flash Storage']

In [10]:
for value in listtoapply:
    applychanges(value)

In [11]:
df.head(2)

,Company,TypeName,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,first,Layer1HDD,Layer1SSD,Layer1Hybrid,Layer1Flash Storage
0,Apple,Ultrabook,Intel Core i5 2.3GHz,8,128 SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,0,1,226.983005,Intel Core i5,128 SSD,0,1,0,0
1,Apple,Ultrabook,Intel Core i5 1.8GHz,8,128 Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,0,127.677940,Intel Core i5,128 Flash Storage,0,0,0,1

In [12]:
df['first'] = df['first'].str.replace(r'\D', '', regex=True)

In [13]:
df['first'] = pd.to_numeric(df['first'], errors='coerce')

In [14]:
df['Second'] = newdf[1]

In [15]:
def applychanges1(value):
    
    df['Layer2'+value] = df['Second'].apply(lambda x:1 if value in x else 0)

In [16]:
listtoapply1 = ['HDD','SSD','Hybrid','Flash Storage']

In [17]:
df['Second'] = df['Second'].fillna("0")

In [18]:
for value in listtoapply1:
    applychanges1(value)

In [19]:
df.head(2)

,Company,TypeName,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,TouchScreen,...,first,Layer1HDD,Layer1SSD,Layer1Hybrid,Layer1Flash Storage,Second,Layer2HDD,Layer2SSD,Layer2Hybrid,Layer2Flash Storage
0,Apple,Ultrabook,Intel Core i5 2.3GHz,8,128 SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,0,...,128,0,1,0,0,0,0,0,0,0
1,Apple,Ultrabook,Intel Core i5 1.8GHz,8,128 Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,...,128,0,0,0,1,0,0,0,0,0

In [20]:
df['Second'] = df['Second'].str.replace(r'\D', '', regex=True)

In [21]:
df['first'] = df['first'].astype('int')
df['Second'] = df['Second'].astype('int')

In [22]:
df["HDD"]=(df["first"]*df["Layer1HDD"]+df["Second"]*df["Layer2HDD"])
df["SSD"]=(df["first"]*df["Layer1SSD"]+df["Second"]*df["Layer2SSD"])
df["Hybrid"]=(df["first"]*df["Layer1Hybrid"]+df["Second"]*df["Layer2Hybrid"])
df["Flash_Storage"]=(df["first"]*df["Layer1Flash Storage"]+df["Second"]*df["Layer2Flash Storage"])

In [23]:
df.drop(columns=['first', 'Second', 'Layer1HDD', 'Layer1SSD', 'Layer1Hybrid',
       'Layer1Flash Storage', 'Layer2HDD', 'Layer2SSD', 'Layer2Hybrid',
       'Layer2Flash Storage'],inplace=True)

In [24]:
df.head(2)

,Company,TypeName,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Hybrid,Flash_Storage
0,Apple,Ultrabook,Intel Core i5 2.3GHz,8,128 SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,0,1,226.983005,Intel Core i5,0,128,0,0
1,Apple,Ultrabook,Intel Core i5 1.8GHz,8,128 Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,0,127.677940,Intel Core i5,0,0,0,128

In [25]:
df.drop(columns=['Memory', 'Cpu'],inplace=True)

In [26]:
df.head(2)

,Company,TypeName,Ram,Gpu,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Hybrid,Flash_Storage
0,Apple,Ultrabook,8,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,0,1,226.983005,Intel Core i5,0,128,0,0
1,Apple,Ultrabook,8,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,0,127.677940,Intel Core i5,0,0,0,128

In [27]:
df.to_csv("C:\\Users\\amitm\\Desktop\\basic ml project\\data\\fourth_clean.csv", index=False)